### ISSUE TITLE
Cannot import Ubuntu 20.04 prompt

### ISSUE THREAD

**Issue by jxu** [Scriptim/bash-prompt-generator#26]
Sorry for the issue spam. Here is the default PS1 that comes with my Ubuntu 20.04:

    \[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$

Pasting this into the website will make it complain about `debian_chroot`

**Comment by Scriptim** [comment]
The `${debian_chroot:+($debian_chroot)}` syntax should work now with 817e013. However, the Debian prompt uses a different syntax for color escape codes which is not supported by the generator/parser as of now.

**Comment by Scriptim** [comment]
Escape sequences using `\033` (octal) or `\x1b` (hexadecimal) instead of `\e` are now supported in the parser with 6d9f95226188ee5ea4af46776db3ed689ff7152e. The generator will still always produce `\e`.

The `\[\e]0;...\a\]` escape syntax for setting the Xterm window title (see [here](https://en.wikipedia.org/wiki/ANSI_escape_code#OSC_(Operating_System_Command)_sequences)) is also supported via the *Set Window Title* element with 043f37a8a2288eec163340968d515081bf0e8dcd.

Importing the above prompts should work now; please let me know if it doesn't.
